### ISSUE TITLE
局部刷新

### ISSUE THREAD

**Issue by hukejia** [chendongMarch/QuickRv#2]
组装模式，局部刷新LightItemBinder里的onBindView不执行，执行的是外面adapter的，子view的点击事件也只能在LightItemBinder里写，点击事件是根据data的状态做不同的处理，但是LightItemBinder里的onBindView没有执行，data就没有更新，这种场景怎么处理

**Comment by chendongMarch** [comment]
我刚做了一版重构，有没有兴趣关注一下？

**Comment by hukejia** [comment]
> 我刚做了一版重构，有没有兴趣关注一下？

下个项目我尝试下，关于局部刷新我还有个问题，有一种场景，是根据全局的变量控制刷新的，而不是比对data，我现在的做法是data里定义一个，全局变量变了的时候更改所有data里的变量，再调用list的更新，感觉这种做法太麻烦了

**Comment by chendongMarch** [comment]
> > 我刚做了一版重构，有没有兴趣关注一下？
> 
> 下个项目我尝试下，关于局部刷新我还有个问题，有一种场景，是根据全局的变量控制刷新的，而不是比对data，我现在的做法是data里定义一个，全局变量变了的时候更改所有data里的变量，再调用list的更新，感觉这种做法太麻烦了

UI 的更新还是应该以数据为驱动的，数据没有改变也不需要更新显示了，我不是很清楚你这个场景是什么意思？可以详细说说。可以加我qq 1101873740 我们讨论下
